<?php

/**
 * @file
 * Contains inline_funnel.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function inline_funnel_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the inline_funnel module.
    case 'help.page.inline_funnel':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Verisure Inline Funnel') . '</p>';
      $output .= '<p>' . t('In order to make the inline funnel work the block needs to be rendered and the funnel host should be defined in the block configuration.') . '</p>';
      return $output;

    default:
  }
}
